### ISSUE TITLE
Link broken in readme

### ISSUE THREAD

**Issue by bbkr** [p6-pdf/PDF-ISO_32000-p6#4]
a copy of the [PDF-32000 specification](https://github.com/pdf-raku/PDF-ISO_32000-raku/blob/master/src/PDF32000_2008.pdf)

**Comment by dwarring** [comment]
Thanks, the README was out of date. The specification is now fetched via `wget` to reduce the distribution size. Fixed in 0.0.12, uploaded to zef.
